#############################################################################
# Makefile for building froot
# Generated by tmake at 09:55, 2002/06/08
#     Project: froot
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	arm-linux-gcc
CXX	=	arm-linux-g++
CFLAGS	=	-pipe -Wall -W -g
CXXFLAGS=	-pipe -DQT_QWS_EBX -DQT_QWS_CUSTOM -DQWS -fno-exceptions -fno-rtti -Wall -W -g
INCPATH	=	-I$(QPEDIR)/include -I$(QTDIR)/include
LINK	=	arm-linux-gcc
LFLAGS	=	
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -lqpe -lqte
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	AimingState.h \
		GameState.h \
		Launcher.h \
		PieceSlot.h \
		DangerBar.h \
		GameWidget.h \
		LauncherTurnState.h \
		RemoveState.h \
		FrootApp.h \
		Globals.h \
		MovingState.h \
		ScoreBoard.h \
		GameBoard.h \
		HighscoreTable.h \
		Piece.h \
		GameOverState.h \
		HighscoreWidget.h \
		PieceCounter.h \
		GameSettings.h \
		IdleState.h \
		PieceFactory.h \
		NameInputDialog.h \
		SoundPlayer.h
SOURCES =	AimingState.cpp \
		GameState.cpp \
		Launcher.cpp \
		PieceSlot.cpp \
		DangerBar.cpp \
		GameWidget.cpp \
		LauncherTurnState.cpp \
		RemoveState.cpp \
		FrootApp.cpp \
		Globals.cpp \
		MovingState.cpp \
		ScoreBoard.cpp \
		GameBoard.cpp \
		HighscoreTable.cpp \
		Piece.cpp \
		main.cpp \
		GameOverState.cpp \
		HighscoreWidget.cpp \
		PieceCounter.cpp \
		GameSettings.cpp \
		IdleState.cpp \
		PieceFactory.cpp \
		NameInputDialog.cpp \
		SoundPlayer.cpp
OBJECTS =	AimingState.o \
		GameState.o \
		Launcher.o \
		PieceSlot.o \
		DangerBar.o \
		GameWidget.o \
		LauncherTurnState.o \
		RemoveState.o \
		FrootApp.o \
		Globals.o \
		MovingState.o \
		ScoreBoard.o \
		GameBoard.o \
		HighscoreTable.o \
		Piece.o \
		main.o \
		GameOverState.o \
		HighscoreWidget.o \
		PieceCounter.o \
		GameSettings.o \
		IdleState.o \
		PieceFactory.o \
		NameInputDialog.o \
		SoundPlayer.o \
		MenuWidget.o \
		NameInputDialogBase.o \
		OptionsDialog.o \
		AboutWidget.o
INTERFACES =	MenuWidget.ui \
		NameInputDialogBase.ui \
		OptionsDialog.ui \
		AboutWidget.ui
UICDECLS =	MenuWidget.h \
		NameInputDialogBase.h \
		OptionsDialog.h \
		AboutWidget.h
UICIMPLS =	MenuWidget.cpp \
		NameInputDialogBase.cpp \
		OptionsDialog.cpp \
		AboutWidget.cpp
SRCMOC	=	moc_Launcher.cpp \
		moc_DangerBar.cpp \
		moc_GameWidget.cpp \
		moc_FrootApp.cpp \
		moc_ScoreBoard.cpp \
		moc_GameBoard.cpp \
		moc_HighscoreTable.cpp \
		moc_GameOverState.cpp \
		moc_HighscoreWidget.cpp \
		moc_GameSettings.cpp \
		moc_SoundPlayer.cpp \
		moc_MenuWidget.cpp \
		moc_NameInputDialogBase.cpp \
		moc_OptionsDialog.cpp \
		moc_AboutWidget.cpp
OBJMOC	=	moc_Launcher.o \
		moc_DangerBar.o \
		moc_GameWidget.o \
		moc_FrootApp.o \
		moc_ScoreBoard.o \
		moc_GameBoard.o \
		moc_HighscoreTable.o \
		moc_GameOverState.o \
		moc_HighscoreWidget.o \
		moc_GameSettings.o \
		moc_SoundPlayer.o \
		moc_MenuWidget.o \
		moc_NameInputDialogBase.o \
		moc_OptionsDialog.o \
		moc_AboutWidget.o
DIST	=	
TARGET	=	froot
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: froot.pro
	tmake froot.pro -o Makefile

dist:
	$(TAR) froot.tar froot.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) froot.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

AimingState.o: AimingState.cpp \
		AimingState.h \
		LauncherTurnState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		Launcher.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		GameWidget.h

GameState.o: GameState.cpp \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

Launcher.o: Launcher.cpp \
		Launcher.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		GameBoard.h \
		Piece.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h

PieceSlot.o: PieceSlot.cpp \
		PieceSlot.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		Globals.h \
		Piece.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		GameBoard.h

DangerBar.o: DangerBar.cpp \
		DangerBar.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h

GameWidget.o: GameWidget.cpp \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		DangerBar.h \
		Launcher.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		GameBoard.h \
		GameSettings.h \
		Piece.h \
		PieceSlot.h \
		PieceCounter.h \
		PieceFactory.h \
		ScoreBoard.h \
		AimingState.h \
		LauncherTurnState.h \
		GameState.h \
		MovingState.h \
		RemoveState.h \
		IdleState.h \
		GameOverState.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h

LauncherTurnState.o: LauncherTurnState.cpp \
		LauncherTurnState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		Launcher.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h

RemoveState.o: RemoveState.cpp \
		RemoveState.h \
		LauncherTurnState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		GameBoard.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		PieceSlot.h \
		PieceCounter.h \
		Piece.h

FrootApp.o: FrootApp.cpp \
		FrootApp.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		MenuWidget.h \
		GameWidget.h \
		AboutWidget.h \
		OptionsDialog.h \
		GameSettings.h \
		HighscoreTable.h \
		HighscoreWidget.h \
		NameInputDialog.h \
		NameInputDialogBase.h \
		SoundPlayer.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qcombobox.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qcheckbox.h

Globals.o: Globals.cpp \
		Globals.h

MovingState.o: MovingState.cpp \
		MovingState.h \
		LauncherTurnState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		Globals.h \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		GameBoard.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		PieceSlot.h \
		Piece.h

ScoreBoard.o: ScoreBoard.cpp \
		ScoreBoard.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		GameSettings.h

GameBoard.o: GameBoard.cpp \
		GameBoard.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		Globals.h \
		Piece.h \
		PieceSlot.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h

HighscoreTable.o: HighscoreTable.cpp \
		HighscoreTable.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h

Piece.o: Piece.cpp \
		Piece.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		GameBoard.h

main.o: main.cpp \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		FrootApp.h

GameOverState.o: GameOverState.cpp \
		GameOverState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		GameBoard.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		ScoreBoard.h \
		/opt/Qtopia/sharp/include/qtimer.h

HighscoreWidget.o: HighscoreWidget.cpp \
		HighscoreWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		HighscoreTable.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h

PieceCounter.o: PieceCounter.cpp \
		PieceCounter.h \
		Piece.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h

GameSettings.o: GameSettings.cpp \
		GameSettings.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h

IdleState.o: IdleState.cpp \
		IdleState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

PieceFactory.o: PieceFactory.cpp \
		PieceFactory.h \
		Piece.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h

NameInputDialog.o: NameInputDialog.cpp \
		NameInputDialog.h \
		NameInputDialogBase.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

SoundPlayer.o: SoundPlayer.cpp \
		SoundPlayer.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpe/sound.h \
		/opt/Qtopia/sharp/include/qsound.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h

MenuWidget.h: MenuWidget.ui
	$(UIC) MenuWidget.ui -o $(INTERFACE_DECL_PATH)/MenuWidget.h

MenuWidget.cpp: MenuWidget.ui
	$(UIC) MenuWidget.ui -i MenuWidget.h -o MenuWidget.cpp

NameInputDialogBase.h: NameInputDialogBase.ui
	$(UIC) NameInputDialogBase.ui -o $(INTERFACE_DECL_PATH)/NameInputDialogBase.h

NameInputDialogBase.cpp: NameInputDialogBase.ui
	$(UIC) NameInputDialogBase.ui -i NameInputDialogBase.h -o NameInputDialogBase.cpp

OptionsDialog.h: OptionsDialog.ui
	$(UIC) OptionsDialog.ui -o $(INTERFACE_DECL_PATH)/OptionsDialog.h

OptionsDialog.cpp: OptionsDialog.ui
	$(UIC) OptionsDialog.ui -i OptionsDialog.h -o OptionsDialog.cpp

AboutWidget.h: AboutWidget.ui
	$(UIC) AboutWidget.ui -o $(INTERFACE_DECL_PATH)/AboutWidget.h

AboutWidget.cpp: AboutWidget.ui
	$(UIC) AboutWidget.ui -i AboutWidget.h -o AboutWidget.cpp

MenuWidget.o: MenuWidget.cpp

NameInputDialogBase.o: NameInputDialogBase.cpp

OptionsDialog.o: OptionsDialog.cpp

AboutWidget.o: AboutWidget.cpp

moc_Launcher.o: moc_Launcher.cpp \
		Launcher.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h

moc_DangerBar.o: moc_DangerBar.cpp \
		DangerBar.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

moc_GameWidget.o: moc_GameWidget.cpp \
		GameWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

moc_FrootApp.o: moc_FrootApp.cpp \
		FrootApp.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

moc_ScoreBoard.o: moc_ScoreBoard.cpp \
		ScoreBoard.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h

moc_GameBoard.o: moc_GameBoard.cpp \
		GameBoard.h \
		/opt/Qtopia/sharp/include/qcanvas.h \
		/opt/Qtopia/sharp/include/qbitmap.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qgdict.h

moc_HighscoreTable.o: moc_HighscoreTable.cpp \
		HighscoreTable.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qregexp.h

moc_GameOverState.o: moc_GameOverState.cpp \
		GameOverState.h \
		GameState.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h

moc_HighscoreWidget.o: moc_HighscoreWidget.cpp \
		HighscoreWidget.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

moc_GameSettings.o: moc_GameSettings.cpp \
		GameSettings.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h

moc_SoundPlayer.o: moc_SoundPlayer.cpp \
		SoundPlayer.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h

moc_MenuWidget.o: moc_MenuWidget.cpp \
		MenuWidget.h

moc_NameInputDialogBase.o: moc_NameInputDialogBase.cpp \
		NameInputDialogBase.h

moc_OptionsDialog.o: moc_OptionsDialog.cpp \
		OptionsDialog.h

moc_AboutWidget.o: moc_AboutWidget.cpp \
		AboutWidget.h

moc_Launcher.cpp: Launcher.h
	$(MOC) Launcher.h -o moc_Launcher.cpp

moc_DangerBar.cpp: DangerBar.h
	$(MOC) DangerBar.h -o moc_DangerBar.cpp

moc_GameWidget.cpp: GameWidget.h
	$(MOC) GameWidget.h -o moc_GameWidget.cpp

moc_FrootApp.cpp: FrootApp.h
	$(MOC) FrootApp.h -o moc_FrootApp.cpp

moc_ScoreBoard.cpp: ScoreBoard.h
	$(MOC) ScoreBoard.h -o moc_ScoreBoard.cpp

moc_GameBoard.cpp: GameBoard.h
	$(MOC) GameBoard.h -o moc_GameBoard.cpp

moc_HighscoreTable.cpp: HighscoreTable.h
	$(MOC) HighscoreTable.h -o moc_HighscoreTable.cpp

moc_GameOverState.cpp: GameOverState.h
	$(MOC) GameOverState.h -o moc_GameOverState.cpp

moc_HighscoreWidget.cpp: HighscoreWidget.h
	$(MOC) HighscoreWidget.h -o moc_HighscoreWidget.cpp

moc_GameSettings.cpp: GameSettings.h
	$(MOC) GameSettings.h -o moc_GameSettings.cpp

moc_SoundPlayer.cpp: SoundPlayer.h
	$(MOC) SoundPlayer.h -o moc_SoundPlayer.cpp

moc_MenuWidget.cpp: MenuWidget.h
	$(MOC) MenuWidget.h -o moc_MenuWidget.cpp

moc_NameInputDialogBase.cpp: NameInputDialogBase.h
	$(MOC) NameInputDialogBase.h -o moc_NameInputDialogBase.cpp

moc_OptionsDialog.cpp: OptionsDialog.h
	$(MOC) OptionsDialog.h -o moc_OptionsDialog.cpp

moc_AboutWidget.cpp: AboutWidget.h
	$(MOC) AboutWidget.h -o moc_AboutWidget.cpp

